# Generated by Django 4.2.1 on 2023-06-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=200)),
                ('Apellidos', models.CharField(max_length=200)),
                ('Ubcacion', models.CharField(max_length=200)),
                ('Direccion', models.CharField(max_length=200)),
                ('contraseña', models.CharField(max_length=200)),
                ('correo', models.CharField(max_length=200)),
                ('tipo_doc', models.IntegerField(choices=[(0, 'Cédula de Ciudadanía'), (1, 'Cédula de Extranjería'), (2, 'Pasaporte')])),
                ('N_doc', models.IntegerField()),
                ('N_cel', models.IntegerField()),
                ('Medio_trans', models.CharField(max_length=200)),
                ('Fecha_exp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
